version: '3.8'
services:
  gosegmentation:
    container_name: gosegmentation
    build:
      context: .
    env_file:
      - .env
    networks:
      - shared
    ports:
      - '1350:1350'
    depends_on:
      - pgl_db
    # volumes:
    #   - logs:/segmentation/logs
    restart: always
  pgl_db:
    container_name: pgl_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - shared
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-data:
    driver: local


networks:
  shared:
    driver: bridge

